# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run in ubuntu 22.04
        run: |
          docker build -t alliance-auto-aim-test-build-ubuntu2204 -f ${{github.workspace}}/tests/docker/ubuntu22.04.build.dockerfile ${{github.workspace}}
          docker run --rm alliance-auto-aim-test-build-ubuntu2204
